### Create Encounter
POST http://localhost:8080/api/encounters
Content-Type: application/json

### Add Combatant (replace {encounter-id} with actual ID from above)
POST http://localhost:8080/api/encounters/<encounter-id>/combatants
Content-Type: application/json

{
  "type": "ENEMY",
  "name": "Goblin",
  "templateId": "goblin",
  "maxHP": 7,
  "ac": 15,
  "initiativeModifier": 2
}

### Add Player Character
POST http://localhost:8080/api/encounters/<encounter-id>/combatants
Content-Type: application/json

{
  "type": "PC",
  "name": "Zeraack",
  "templateId": "",
  "maxHP": 30,
  "ac": 15,
  "initiativeModifier": 3
}

### Remove a combatant
DELETE http://localhost:8080/api/encounters/<encounter-id>/combatants/<combatant-id>

### Start the actual encounter
POST http://localhost:8080/api/encounters/<encounter-id>/start
Content-Type: application/json

{
  "playerInitiatives": {
    "<combatantId>": 18
  }
}

### Deal damage to a combatant
POST http://localhost:8080/api/encounters/<encounter-id>/combatants/<combatant-id>/damage
Content-type: application/json

{
  "amount": 5
}

### Heal a combatant
POST http://localhost:8080/api/encounters/<encounter-id>/combatants/<combatant-id>/heal
Content-type: application/json

{
  "amount": 5
}

### Go to next turn
POST http://localhost:8080/api/encounters/<encounter-id>/next-turn

### Go to previous turn
POST http://localhost:8080/api/encounters/<encounter-id>/previous-turn

### Get encounter information
GET http://localhost:8080/api/encounters/<encounter-id>